// FULL PRETTIER SCHEMA: v3.3.2 / 2024-06-30
// http://json.schemastore.org/prettierrc
// NOTE: annotations generated by ChatGPT

// NOTE: eslint-plugin-prettier will TURN OFF the following ESLint rules:
// 1. "arrow-body-style": "off"
// 2. "prefer-arrow-callback": "off"

const prettierDefaults = {
  arrowParens: 'always', // (default: 'always' | 'avoid') - Include parentheses around a sole arrow function parameter.
  bracketSameLine: false, // (default: false | true) - Put > of a multi-line HTML (HTML, JSX, Vue, Angular) element at the end of the last line instead of being alone on the next line.
  bracketSpacing: true, // (default: true | false) - Print spaces between brackets.
  cursorOffset: -1, // (default: -1) - Cursor offset for formatting a selected range. -1 means format the whole document.
  embeddedLanguageFormatting: 'auto', // (default: 'auto' | 'off') - Control whether Prettier formats quoted code embedded in the file.
  endOfLine: 'lf', // (default: 'lf' | 'crlf' | 'cr' | 'auto') - Line ending setting.
  hexLiterals: 'uppercase',
  htmlWhitespaceSensitivity: 'css', // (default: 'css' | 'strict' | 'ignore') - How to handle whitespaces in HTML.
  insertPragma: false, // (default: false | true) - Insert a special @format marker at the top of files specifying that the file has been formatted with Prettier.
  jsxSingleQuote: false, // (default: false | true) - Use single quotes instead of double quotes in JSX.
  printWidth: 80, // (default: 80) - The line length where Prettier will try to wrap.
  proseWrap: 'preserve', // (default: 'preserve' | 'always' | 'never') - How to wrap prose.
  quoteProps: 'as-needed', // (default: 'as-needed' | 'consistent' | 'preserve') - Change when properties in objects are quoted.
  rangeEnd: Infinity, // (default: Infinity) - Format code ending at a given character offset (exclusive).
  rangeStart: 0, // (default: 0) - Format code starting at a given character offset.
  requirePragma: false, // (default: false | true) - Require a special comment to format a file.
  semi: true, // (default: true | false) - Print semicolons.
  singleQuote: false, // (default: false | true) - Use single quotes instead of double quotes.
  tabWidth: 2, // (default: 2) - Number of spaces per indentation level.
  trailingComma: 'es5', // (default: 'es5' | 'none' | 'all') - Print trailing commas wherever possible when multi-line.
  useTabs: false, // (default: false | true) - Indent with tabs instead of spaces.
  vueIndentScriptAndStyle: false, // (default: false | true) - Indent <script> and <style> tags in Vue files.
  plugins: [], // (default: []) - Path to Prettier plugins.
  overrides: [], // (default: []) - Override settings for specific file patterns.
};

const customOverrides = {
  printWidth: 110,
  singleQuote: true,
  trailingComma: 'all',
  quoteProps: 'consistent',
};

module.exports = {
  ...prettierDefaults,
  ...customOverrides,
};
